---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'cfn-modules: ALB redirect to HTTPS'
# cfn-modules:implements()
Parameters:
  AlbListenerModule:
    Description: 'Stack name of alb-listener module.'
    Type: String
  RedirectPort:
    Description: 'Port that is redirected to using the HTTPS protocol.'
    Type: Number
    Default: 443
  Priority:
    Description: 'The priority for the rule. Elastic Load Balancing evaluates rules in priority order, from the lowest value to the highest value. If a request satisfies a rule, Elastic Load Balancing ignores all subsequent rules. A target group can have only one rule with a given priority.'
    Type: Number
    Default: 1
    ConstraintDescription: 'Must be in the range [1-99999]'
    MinValue: 1
    MaxValue: 99999
  HostPattern:
    Description: 'Optional host pattern (you can specify HostPattern and/or PathPattern).'
    Type: String
    Default: ''
    ConstraintDescription: 'Must not be longer than 255'
    MaxLength: 255
  PathPattern:
    Description: 'Optional path pattern (you can specify PathPattern and/or HostPattern).'
    Type: String
    Default: '/*'
    ConstraintDescription: 'Must not be longer than 255'
    MaxLength: 255
Conditions:
  HasPathPattern: !Not [!Equals [!Ref PathPattern, '']]
  HasHostPattern: !Not [!Equals [!Ref HostPattern, '']]
Resources:
  ListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
      - RedirectConfig:
          Port: !Ref RedirectPort
          Protocol: HTTPS
          StatusCode: 'HTTP_301'
        Type: redirect
      Conditions:
      - !If [HasHostPattern, {Field: host-header, Values: [!Ref HostPattern]}, !Ref 'AWS::NoValue']
      - !If [HasPathPattern, {Field: path-pattern, Values: [!Ref PathPattern]}, !Ref 'AWS::NoValue']
      ListenerArn: {'Fn::ImportValue': !Sub '${AlbListenerModule}-Arn'}
      Priority: !Ref Priority
Outputs:
  ModuleId:
    Value: 'alb-redirect-to-https'
  ModuleVersion:
    Value: '1.0.0'
  StackName:
    Value: !Ref 'AWS::StackName'
